# Vetores 2D

In [126]:
import numpy as np

In [127]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

In [128]:
# Vetor 2D
x

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
y = x.T

In [130]:
y

array([[1, 4],
       [2, 5],
       [3, 6]])

In [131]:
y[2, 1] = 77

In [132]:
y

array([[ 1,  4],
       [ 2,  5],
       [ 3, 77]])

In [133]:
x

array([[ 1,  2,  3],
       [ 4,  5, 77]])

In [134]:
y2 = x.copy().T

In [135]:
y2

array([[ 1,  4],
       [ 2,  5],
       [ 3, 77]])

In [136]:
y2[0, 0] = 888

In [137]:
y2

array([[888,   4],
       [  2,   5],
       [  3,  77]])

In [138]:
x

array([[ 1,  2,  3],
       [ 4,  5, 77]])

## Fatiamento de vetores 2D

In [139]:
for i in range(2, 7):
    print(i)

2
3
4
5
6


In [140]:
[range(1-1, i+4) for i in [1, 2, 3, 4]]

[range(0, 5), range(0, 6), range(0, 7), range(0, 8)]

In [141]:
x1 = np.array([range(i-1, i+4) for i in [1, 2, 3, 4]])

In [142]:
x1

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [143]:
x1.shape

(4, 5)

In [144]:
# coletando linha
l2 = x1[1, :]

In [145]:
l2

array([1, 2, 3, 4, 5])

In [146]:
# Coletando coluna
c4 = x1[:, 3]

In [147]:
c4

array([3, 4, 5, 6])

In [148]:
sm = x1[2:, 3:]

In [149]:
sm

array([[5, 6],
       [6, 7]])

### Fatiamento de submatriz

In [150]:
sm2 = x1[1:3, 1:3]

In [151]:
sm2

array([[2, 3],
       [3, 4]])

# |
# |
# |
# |

In [152]:
x1 = np.array([range(i-1, i+4) for i in [1, 2, 3, 4]])

In [153]:
x1

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [154]:
M1 = x1[1:3, 1:3]

In [155]:
M1

array([[2, 3],
       [3, 4]])

In [156]:
M2 = x1[0:2, 2:4]

In [157]:
M2

array([[2, 3],
       [3, 4]])

In [158]:
M3 = x1[0:3, 3:]

In [159]:
M3

array([[3, 4],
       [4, 5],
       [5, 6]])

### Arrays 2D especiais

In [160]:
np.empty((5, 3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.81019663e-310]])

In [161]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [162]:
# Matriz identidade
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [163]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

## Matrizes Importantes Álgebra

In [164]:
xd = np.diagflat([[1, 4, 7, -9, 8]])

In [165]:
xd

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  7,  0,  0],
       [ 0,  0,  0, -9,  0],
       [ 0,  0,  0,  0,  8]])

In [166]:
d = np.diag(xd)

In [167]:
d

array([ 1,  4,  7, -9,  8])

### Soma os elementos da diagonal principal - Traço

In [168]:
trace = np.trace(xd)

In [169]:
trace

11

# Matriz de Vandermond

In [170]:
a = np.array([1, 2, 3, 4, 5])

n = 5

v = np.vander(a, n)

In [171]:
v

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

### Como copiar submatrizes - Atenção !

In [172]:
y1 = v[0:2, 3:5]

In [173]:
y1

array([[1, 1],
       [2, 1]])

In [174]:
y2 = v[3:5, 0:2]

In [175]:
y2

array([[256,  64],
       [625, 125]])

In [176]:
y2 = y2.T

In [177]:
v

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [178]:
v[0:2, 3:5] = y1

In [179]:
v

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [180]:
v[3:5, 0:2] = y2

In [181]:
v

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256, 625,  16,   4,   1],
       [ 64, 125,  25,   5,   1]])

In [ ]:
y3 = v[3:5, 0:2].copy()

y4 = v[0:2, 3:5].copy()