# Vetores 3D

In [127]:
import numpy as np

In [128]:
v3 = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
v3

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [129]:
v3.shape

(1, 4, 2)

In [130]:
v4 = np.array([[[1, 2], [3, 4]],   [[5, 6], [7, 8]]])
v4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [131]:
v4.shape

(2, 2, 2)

## Reshape  →   Array 3D

In [132]:
a1 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [133]:
a2 = a1.reshape(3, 2, 2)
a2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [134]:
a4 = a1.reshape(3, 1, 4)
a4

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

## Fatiamento de Array 3D


In [135]:
m1 = np.array([[[7, 8, 5], [5, 2, 4], [17, 5, 8]],
               [[6, 7, 1], [4, 1, 1], [6, 2, 11]],
               [[5, 1, 0], [72, 9, 3], [7, 9, 5]]])

m1

array([[[ 7,  8,  5],
        [ 5,  2,  4],
        [17,  5,  8]],

       [[ 6,  7,  1],
        [ 4,  1,  1],
        [ 6,  2, 11]],

       [[ 5,  1,  0],
        [72,  9,  3],
        [ 7,  9,  5]]])

In [136]:
m1_n = m1[:2, 1:, 1:]

m1_n

array([[[ 2,  4],
        [ 5,  8]],

       [[ 1,  1],
        [ 2, 11]]])

In [137]:
m1_n2 = m1[2, :, :]

m1_n2

array([[ 5,  1,  0],
       [72,  9,  3],
       [ 7,  9,  5]])

In [138]:
m1[-1, :, :]

array([[ 5,  1,  0],
       [72,  9,  3],
       [ 7,  9,  5]])

## Transformar Array 3D para 2D

In [139]:
g1 = np.array([[[1, 9],
                [1, 2]],
               [[1, 2],
                [1, 9]],
               [[4, 3],
                [1, 3]],
               [[2, 5],
                [6, 2]]])

g1

array([[[1, 9],
        [1, 2]],

       [[1, 2],
        [1, 9]],

       [[4, 3],
        [1, 3]],

       [[2, 5],
        [6, 2]]])

In [140]:
g1.shape

(4, 2, 2)

In [141]:
g2 = np.reshape(g1, (4, 4))

g2

array([[1, 9, 1, 2],
       [1, 2, 1, 9],
       [4, 3, 1, 3],
       [2, 5, 6, 2]])

In [142]:
np.reshape(g2, (4, 2, 2))

array([[[1, 9],
        [1, 2]],

       [[1, 2],
        [1, 9]],

       [[4, 3],
        [1, 3]],

       [[2, 5],
        [6, 2]]])

In [143]:
# Transposta de um Vetor 3D

In [144]:
vet = np.array([[[7, 8, 5], [5, 2, 4], [17, 5, 8]],
                [[6, 7, 1], [4, 1, 1], [6, 2, 1]],
                [[5, 1, 0], [72, 9, 3], [7, 9, 5]]])
vet

array([[[ 7,  8,  5],
        [ 5,  2,  4],
        [17,  5,  8]],

       [[ 6,  7,  1],
        [ 4,  1,  1],
        [ 6,  2,  1]],

       [[ 5,  1,  0],
        [72,  9,  3],
        [ 7,  9,  5]]])

In [145]:
vet.transpose()

array([[[ 7,  6,  5],
        [ 5,  4, 72],
        [17,  6,  7]],

       [[ 8,  7,  1],
        [ 2,  1,  9],
        [ 5,  2,  9]],

       [[ 5,  1,  0],
        [ 4,  1,  3],
        [ 8,  1,  5]]])

In [146]:
vet.T

array([[[ 7,  6,  5],
        [ 5,  4, 72],
        [17,  6,  7]],

       [[ 8,  7,  1],
        [ 2,  1,  9],
        [ 5,  2,  9]],

       [[ 5,  1,  0],
        [ 4,  1,  3],
        [ 8,  1,  5]]])

In [147]:
vet[0].T

array([[ 7,  5, 17],
       [ 8,  2,  5],
       [ 5,  4,  8]])

In [148]:
vet[0, :, :].T

array([[ 7,  5, 17],
       [ 8,  2,  5],
       [ 5,  4,  8]])

In [149]:
vet[1, :, :].T

array([[6, 4, 6],
       [7, 1, 2],
       [1, 1, 1]])

## Somar elementos de vetor 3D

In [150]:
vet2 = np.array([[[1, 1, 0], [2, 2, 2], [3, 2, 3]],
                 [[1, 0, 3], [2, 1, 2], [2, -1, 2]],
                 [[2, 1, 2], [1, 0, 1], [1, 0, 1]]])

vet2

array([[[ 1,  1,  0],
        [ 2,  2,  2],
        [ 3,  2,  3]],

       [[ 1,  0,  3],
        [ 2,  1,  2],
        [ 2, -1,  2]],

       [[ 2,  1,  2],
        [ 1,  0,  1],
        [ 1,  0,  1]]])

In [151]:
np.sum(vet2)

37

In [152]:
np.sum(vet2, axis=0)

array([[4, 2, 5],
       [5, 3, 5],
       [6, 1, 6]])

In [153]:
np.sum(vet2, axis=1)

array([[6, 5, 5],
       [5, 0, 7],
       [4, 1, 4]])

## Estatísticas descritivas vetor 3D
#### Min, Max, Mean, Std

In [154]:
np.min(vet2)

-1

In [155]:
np.max(vet2)

3

In [156]:
np.mean(vet2)

1.3703703703703705

In [157]:
np.std(vet2)

0.9868824144054984

In [158]:
np.min(vet2, axis=0)

array([[ 1,  0,  0],
       [ 1,  0,  1],
       [ 1, -1,  1]])

In [159]:
np.min(vet2, axis=1)

array([[ 1,  1,  0],
       [ 1, -1,  2],
       [ 1,  0,  1]])

## Funções ones, zeros, eye  ->  vetores 3D

In [160]:
x1 = np.ones((3, 4, 3))
x1

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [161]:
x2 = np.zeros((3, 4, 3))
x2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [162]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [163]:
# x3 = np.eye((3,4))  # Errado

# Salvando, em arquivos, os dados de Array

In [164]:
a = np.array([1, 3, 5, 7])
a

array([1, 3, 5, 7])

In [167]:
a2 = np.vander([1, 3, 5, 7], 5)
a2

array([[   1,    1,    1,    1,    1],
       [  81,   27,    9,    3,    1],
       [ 625,  125,   25,    5,    1],
       [2401,  343,   49,    7,    1]])

In [166]:
np.savetxt('Dados.txt', a, fmt='%d')

In [168]:
np.savetxt('Dados2.txt', a2, fmt='%f')

## Como abrir arquivos txt

In [169]:
u = np.loadtxt('Dados2.txt', dtype=float)
u

array([[1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00],
       [8.100e+01, 2.700e+01, 9.000e+00, 3.000e+00, 1.000e+00],
       [6.250e+02, 1.250e+02, 2.500e+01, 5.000e+00, 1.000e+00],
       [2.401e+03, 3.430e+02, 4.900e+01, 7.000e+00, 1.000e+00]])