# Tipos de imports

In [15]:
import numpy as np 

In [ ]:
# pip freeze  # mostrar versoes de bibliotecas intaladas

In [16]:
a = [1,2,3,4,5]   

In [17]:
type(a)

list

In [18]:
b = np.array([1,2,3,4,5])

In [19]:
b

array([1, 2, 3, 4, 5])

In [20]:
type(b)

numpy.ndarray

Tipos 2 de import

In [21]:
from numpy import *

In [23]:
array([3,4,5])

array([3, 4, 5])

In [24]:
pi

3.141592653589793

In [25]:
cos(0)

1.0

## Nomenclatura

* Vetores

* Matrizes 

Arrays