# Manipulando vetores 2D

In [432]:
import numpy as np

## Geração de números aleatórios

In [433]:
np.random.seed(777)

In [434]:
x = np.random.randint(100, size=(3, 3))

In [435]:
x

array([[47, 59, 38],
       [87, 49, 71],
       [29, 39, 89]])

In [436]:
x1 = np.random.randint(5, size=(3, 3))

In [437]:
x1

array([[2, 0, 2],
       [0, 3, 1],
       [2, 4, 1]])

In [438]:
x2 = np.random.randint(2, size=(10, 10))

In [439]:
x2

array([[1, 1, 1, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 1, 1, 0, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 1, 1, 1, 0, 1]])

## Como filtrar posições de vetores

In [440]:
x

array([[47, 59, 38],
       [87, 49, 71],
       [29, 39, 89]])

In [441]:
r, c = np.where((x >= 5) & (x <= 50))

In [442]:
r

array([0, 0, 1, 2, 2], dtype=int64)

In [443]:
c

array([0, 2, 1, 0, 1], dtype=int64)

In [444]:
valores = x[r, c]

In [445]:
valores

array([47, 38, 49, 29, 39])

## Organizando índices em tuplas

In [446]:
i = list(zip(r, c))

i

[(0, 0), (0, 2), (1, 1), (2, 0), (2, 1)]

In [447]:
[x[j] for j in i]

[47, 38, 49, 29, 39]

### Filtros substituindo valores

In [448]:
a = np.where(((x >= 5) & (x <= 50)), x, 0)

a

array([[47,  0, 38],
       [ 0, 49,  0],
       [29, 39,  0]])

In [449]:
a1 = np.where(((x >= 5) & (x <= 50)), x, 88)

a1

array([[47, 88, 38],
       [88, 49, 88],
       [29, 39, 88]])

In [450]:
a2 = np.where(~((x >= 5) & (x <= 50)), x, 0)

a2

array([[ 0, 59,  0],
       [87,  0, 71],
       [ 0,  0, 89]])

### Modificando valores de submatrizes

In [451]:
x

array([[47, 59, 38],
       [87, 49, 71],
       [29, 39, 89]])

In [452]:
x[0, 0] = 100

x

array([[100,  59,  38],
       [ 87,  49,  71],
       [ 29,  39,  89]])

In [453]:
a2

array([[ 0, 59,  0],
       [87,  0, 71],
       [ 0,  0, 89]])

In [454]:
x[1:3, 0] = 9, 99

x

array([[100,  59,  38],
       [  9,  49,  71],
       [ 99,  39,  89]])

In [455]:
a2

array([[ 0, 59,  0],
       [87,  0, 71],
       [ 0,  0, 89]])

# Técnicas avançadas  de Manipulação de Arrays 2D

In [456]:
np.random.seed(2)

In [457]:
x = np.random.rand(3, 3)
x

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

In [458]:
y = x.copy() + 1
y

array([[1.4359949 , 1.02592623, 1.54966248],
       [1.43532239, 1.4203678 , 1.33033482],
       [1.20464863, 1.61927097, 1.29965467]])

In [459]:
z = y[:, 2].copy()
z

array([1.54966248, 1.33033482, 1.29965467])

In [460]:
# Empilha verticalmente
np.vstack([z, z, z, z])

array([[1.54966248, 1.33033482, 1.29965467],
       [1.54966248, 1.33033482, 1.29965467],
       [1.54966248, 1.33033482, 1.29965467],
       [1.54966248, 1.33033482, 1.29965467]])

#### Função np.reshape e np.hstack

In [461]:
z.T

array([1.54966248, 1.33033482, 1.29965467])

In [462]:
z1 = np.reshape(z, (3, 1))
z1

array([[1.54966248],
       [1.33033482],
       [1.29965467]])

In [463]:
# Empilha horizontalmente

In [464]:
np.hstack([z1, z1, z1, z1])

array([[1.54966248, 1.54966248, 1.54966248, 1.54966248],
       [1.33033482, 1.33033482, 1.33033482, 1.33033482],
       [1.29965467, 1.29965467, 1.29965467, 1.29965467]])

### Transformar Matriz em Vetor

In [465]:
x

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

In [466]:
x.size

9

In [467]:
xf = np.reshape(x, 9)

xf

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
       0.33033482, 0.20464863, 0.61927097, 0.29965467])

In [468]:
xf = np.reshape(x, x.size)

## Split de vetores

In [469]:
v = np.arange(12) + 1
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [470]:
v1, v2 = np.split(v, [3])

In [471]:
v1

array([1, 2, 3])

In [472]:
v2

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [473]:
v_1, v_2, v_3 = np.split(v, 3)

In [474]:
v_1

array([1, 2, 3, 4])

In [475]:
v_2

array([5, 6, 7, 8])

In [476]:
v_3

array([ 9, 10, 11, 12])

In [477]:
w1, w2 = np.split(v, 2)

In [478]:
w1

array([1, 2, 3, 4, 5, 6])

In [479]:
w2

array([ 7,  8,  9, 10, 11, 12])

In [480]:
w_1, w_2 = np.split(v, [2])

In [481]:
w_1

array([1, 2])

In [482]:
w_2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Split de Matrizes

In [483]:
k = np.arange(24).reshape(4, 6)
k

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [484]:
k1, k2, k3 = np.hsplit(k, [2, 4])

In [485]:
k1

array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19]])

In [486]:
k2

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]])

In [487]:
k3

array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])

## Split vertical de matrizes

In [488]:
k

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [489]:
k1, k2 = np.vsplit(k, [2])

In [490]:
k1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [491]:
k2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [492]:
k_v1, k_v2, k_v3, k_v4 = np.vsplit(k, 4)

In [493]:
k_v1

array([[0, 1, 2, 3, 4, 5]])

In [494]:
k_v2

array([[ 6,  7,  8,  9, 10, 11]])

In [495]:
k_v3

array([[12, 13, 14, 15, 16, 17]])

In [496]:
k_v4

array([[18, 19, 20, 21, 22, 23]])

## Concatenando Vetores

In [497]:
c = np.array([1, 2, 4, 7, 8, 9])
c

array([1, 2, 4, 7, 8, 9])

In [498]:
np.concatenate([c, c])

array([1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9])

In [499]:
np.concatenate([np.sqrt(c), c*2])

array([ 1.        ,  1.41421356,  2.        ,  2.64575131,  2.82842712,
        3.        ,  2.        ,  4.        ,  8.        , 14.        ,
       16.        , 18.        ])

In [500]:
np.tile(c, 10)

array([1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9, 1, 2, 4, 7,
       8, 9, 1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9, 1, 2,
       4, 7, 8, 9, 1, 2, 4, 7, 8, 9, 1, 2, 4, 7, 8, 9])

In [503]:
# Matrizes

np.concatenate([k3, k3], axis=1)

array([[ 4,  5,  4,  5],
       [10, 11, 10, 11],
       [16, 17, 16, 17],
       [22, 23, 22, 23]])

In [504]:
np.tile(k3, 10)

array([[ 4,  5,  4,  5,  4,  5,  4,  5,  4,  5,  4,  5,  4,  5,  4,  5,
         4,  5,  4,  5],
       [10, 11, 10, 11, 10, 11, 10, 11, 10, 11, 10, 11, 10, 11, 10, 11,
        10, 11, 10, 11],
       [16, 17, 16, 17, 16, 17, 16, 17, 16, 17, 16, 17, 16, 17, 16, 17,
        16, 17, 16, 17],
       [22, 23, 22, 23, 22, 23, 22, 23, 22, 23, 22, 23, 22, 23, 22, 23,
        22, 23, 22, 23]])