# Lidando com Inf

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 0, 4, 5])

In [3]:
r = a/b

C:\Users\Glaydson Gonçalo\AppData\Local\Temp\ipykernel_12660\2175775285.py:1: RuntimeWarning: divide by zero encountered in divide
  r = a/b


In [4]:
r

array([ 1.,  1., inf,  1.,  1.])

In [5]:
r.sum()

inf

# Como remover inf de um vetor

In [6]:
i = np.where(r == np.inf)

In [7]:
r[i]

array([inf])

In [8]:
def remove_inf(x):
    pi = np.where(x == np.inf)
    i = np.where(x != np.inf)
    return x[i]

In [9]:
remove_inf(r)

array([1., 1., 1., 1.])

In [10]:
r

array([ 1.,  1., inf,  1.,  1.])

In [11]:
np.asarray_chkfinite(r)

ValueError: array must not contain infs or NaNs

In [12]:
try:
    np.asarray_chkfinite(r)
except ValueError:
    rm = remove_inf(r)

In [13]:
rm

array([1., 1., 1., 1.])

# Função que remove inf e diz posição

In [14]:
def remove_inf_pos(x):
    pi = np.where(x == np.inf)
    i = np.where(x != np.inf)
    return x[i], pi

In [15]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a2 = np.array([1, 0, 3, 0, 5, 6, 0, 8, 0])

In [16]:
c1 = a1/a2

C:\Users\Glaydson Gonçalo\AppData\Local\Temp\ipykernel_12660\1747373650.py:1: RuntimeWarning: divide by zero encountered in divide
  c1 = a1/a2


In [17]:
c1

array([ 1., inf,  1., inf,  1.,  1., inf,  1., inf])

In [18]:
c1m, pinf = remove_inf_pos(c1)

In [19]:
c1m

array([1., 1., 1., 1., 1.])

In [20]:
pinf[0]

array([1, 3, 6, 8], dtype=int64)

In [21]:
pinf

(array([1, 3, 6, 8], dtype=int64),)

In [22]:
c1[pinf]

array([inf, inf, inf, inf])

In [23]:
c1[pinf[0]]

array([inf, inf, inf, inf])

# Vetores espaçados linearmente e em escala logarítmica

In [24]:
x = np.linspace(0, 50, num=100)

In [25]:
x

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

## Escala logarítmica

In [26]:
y = np.logspace(1, 4, num=4, base=10)

In [27]:
y

array([   10.,   100.,  1000., 10000.])

## Clonando Arrays

In [29]:
x = np.array([.2, -2.5, 3.43, 5.7, -0.03, 3.7], np.float64)

In [30]:
h = np.empty_like(x)

In [31]:
h

array([1.33511290e-306, 1.11260619e-306, 1.37961370e-306, 1.33511561e-306,
       1.11261027e-306, 3.59412797e-317])

In [32]:
u = np.zeros_like(x)

In [33]:
u

array([0., 0., 0., 0., 0., 0.])

In [34]:
k = np.ones_like(x)

In [35]:
k

array([1., 1., 1., 1., 1., 1.])