## Curso NumPy  - Aula 02

In [1]:
import numpy as np

In [2]:
# Array 1D

In [3]:
x = np.array([])

In [4]:
x

array([], dtype=float64)

In [5]:
y = np.array([1, 2, 3, 4])

In [6]:
y

array([1, 2, 3, 4])

In [7]:
# Array 1D:
y.shape

(4,)

In [8]:
y.dtype

dtype('int32')

In [9]:
# Transposta de um Array

In [10]:
y

array([1, 2, 3, 4])

In [11]:
y.T

array([1, 2, 3, 4])

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [13]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Tipos de Arrays no NumPy

In [15]:
x1 = np.array([1, 2, 3, 4], dtype=np.int32)
x2 = np.array([1, 2, 3, 4], dtype=np.int64)     # padrão - default
x3 = np.array([1, 2, 3, 4], dtype=np.float32)
x4 = np.array([1, 2, 3, 4], dtype=np.float64)   # padrão - default
# x5 = np.array([1,2,3,4], dtype=np.float128)
x6 = np.array([1, 2, 3, 4], dtype=np.complex64)
x7 = np.array([1, 2, 3, 4], dtype=np.complex128)  # padrão - default
# x8 = np.array([1,2,3,4], dtype=np.complex256)

In [16]:
x1

array([1, 2, 3, 4])

In [17]:
x2

array([1, 2, 3, 4], dtype=int64)

In [18]:
x3

array([1., 2., 3., 4.], dtype=float32)

In [19]:
x4

array([1., 2., 3., 4.])

In [20]:
# x5

In [21]:
x6

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex64)

In [22]:
x7

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [23]:
# x8

In [24]:
# Como modificar os tipos

In [25]:
x1

array([1, 2, 3, 4])

In [26]:
x1.dtype

dtype('int32')

In [27]:
# modificando o tipo:
x1.astype(np.float64)

array([1., 2., 3., 4.])

In [28]:
x1

array([1, 2, 3, 4])

In [29]:
# Erro ao obter a dimensão de um vetor 1D

In [30]:
x = np.array([1, 2, 3, 4])

y = np.array([2.1, 4.7, 4.4])

In [31]:
x

array([1, 2, 3, 4])

In [32]:
x.dtype

dtype('int32')

In [33]:
y

array([2.1, 4.7, 4.4])

In [34]:
y.dtype

dtype('float64')

In [35]:
x.shape

(4,)

In [36]:
x.shape[0]

4

In [37]:
# x.shape[1]

In [38]:
xd = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
xd

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
n, m = xd.shape

In [41]:
x.ndim

1

In [42]:
xd.ndim

2

In [43]:
x = np.array([[1, 2, 3], [4, 5, 6]])

x = np.array([2.1, 4.7, 4.4])

In [44]:
if (x.ndim == 1):
    n = x.shape
else:
    n, m = x.shape

In [45]:
m

3

## Indexing e Slicing

In [46]:
x = np.array([1.2, 1.5, 3., 5.2, 7.7])

In [47]:
x

array([1.2, 1.5, 3. , 5.2, 7.7])

In [48]:
a = x[0]

b = x[-1]  # x[4]

In [49]:
a

1.2

In [50]:
b

7.7

In [51]:
z = a+b

In [52]:
z

8.9

In [53]:
x[1:3]

array([1.5, 3. ])

In [54]:
x[1:4]

array([1.5, 3. , 5.2])

In [55]:
x[-2]

5.2

In [56]:
x[-2:]

array([5.2, 7.7])

In [57]:
t1 = x[2:3]

In [58]:
t2 = x[2]

In [59]:
type(t1)

numpy.ndarray

In [60]:
type(t2)

numpy.float64

In [61]:
t1

array([3.])

In [62]:
t2

3.0

In [63]:
t1+t2

array([6.])

In [64]:
t1 == t2

array([ True])

In [65]:
 u = t1 == t2

In [66]:
u.dtype

dtype('bool')

# Avaliações booleanas básicas

In [67]:
x = np.array([1.0, 3., 2.6, 4.3, 7.7, 5.6])
y = np.array([1., 2.6, 3., 4., 7., 5.6])

In [68]:
x

array([1. , 3. , 2.6, 4.3, 7.7, 5.6])

In [69]:
y

array([1. , 2.6, 3. , 4. , 7. , 5.6])

In [70]:
# x.shape[0]
len(y)

6

In [71]:
cmp = x == y

In [72]:
cmp

array([ True, False, False, False, False,  True])

In [73]:
cmp.sum()

2

In [74]:
if (cmp.sum() == len(x)):
    print('Os vetores são iguais')
else:
    print('Os vetores são diferentes')

Os vetores são diferentes


In [75]:
Z1 = np.array([1.0, 3., 2.6, 4.3, 7.7, 5.6])
Z2 = np.array([1.0, 3., 2.6, 4.3, 7.7, 5.6])

In [76]:
cmp2 = Z1 == Z2

In [77]:
cmp2

array([ True,  True,  True,  True,  True,  True])

In [78]:
if (cmp2.sum() == len(Z1)):
    print('Os vetores são iguais')
else:
    print('Os vetores são diferentes')

Os vetores são iguais


### Slicing Saltando Valores 1D

In [79]:
m = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [80]:
m[0:10:3]  # start:end:step

array([ 1,  4,  7, 10])