# Exercício 01 - Avaliar igualdade de vetores e seus elementos

- A partir de dois vetores: x e y;

- Construir uma função/algoritmo para avaliar se dois vetores são iguais ou diferentes; 

- Apresentar os elementos iguais dos vetores;  

- Comparar elemento por elemento dos vetores apresentar índices onde os valores são iguais nos dois vetores.


In [1]:
import numpy as np

In [2]:
x = np.array([1.0, 3., 2.6, 4.3, 7.7, 5.6])
y = np.array([1., 2.6, 3., 4., 7., 5.6])

In [3]:
x = np.array([1.0, 3., 2.6, 4.3, 7.7, 5.6])
y = np.array([1.0, 3., 2.6, 4.3, 7.7, 5.6])

In [4]:
x = np.array([1.5, 3., 2.6, 43.3, 73.7, 5.36])
y = np.array([1.0, 3.3, 2.36, 4.3, 7.73, 5.6])

In [5]:
cmp = x == y

#### Dicas para resolver o exercício 01

In [6]:
cmp.all()

False

In [7]:
cmp.any()

False

In [8]:
np.where(x == y)

(array([], dtype=int64),)

## Solução do Exercício 01

In [9]:
x = np.array([1.0, 3., 2.6, 4.3, 7.7, 5.6])
y = np.array([1., 2.6, 3., 4., 7., 5.6])

In [10]:
cmp = x == y

In [11]:
cmp

array([ True, False, False, False, False,  True])

In [12]:
i = 0

if (cmp.all()):
    print('Todos os elementos são iguais!')
elif (cmp.any()):
    print('Alguns elementos são iguais, são eles:')
    for e in cmp:
        if (e):
            print('%.1f' % y[i])
        i += 1  # i = i + 1

    print('-------------')
    for e in x:
        j = np.where(e == y)  # indexação de igual
        print(j)
        if (j[0].size != 0):
            print(y[j])
else:
    print('Todos os elementos são diferentes.')

Alguns elementos são iguais, são eles:
1.0
5.6
-------------
(array([0], dtype=int64),)
[1.]
(array([2], dtype=int64),)
[3.]
(array([1], dtype=int64),)
[2.6]
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([5], dtype=int64),)
[5.6]
